plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.9.22'
    id 'org.jetbrains.dokka' version '1.9.20'
    id 'signing'
    id "com.vanniktech.maven.publish" version "0.28.0" 
}

kotlin {
    jvmToolchain(8)
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    testImplementation "org.jetbrains.kotlin:kotlin-test"
    testImplementation 'junit:junit:4.13.2'
}

tasks.test {
    useJUnit()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

mavenPublishing {
    publishToMavenCentral(com.vanniktech.maven.publish.SonatypeHost.CENTRAL_PORTAL, true) 
    
    signAllPublications()   

    pom {
        name = "npy"
        description = "NPY and NPZ support for the JVM (Forked)"
        url = "https://github.com/hageldave/npy"
        
        licenses {
            license {
                name = "MIT License"
                url = "https://github.com/hageldave/npy/blob/master/LICENSE"
            }
        }
        developers {
            developer {
                id = "hageldave"
                name = "David Hägele"
                email = "haegele.david@gmail.com"
            }
        }
        scm {
            connection = "scm:git:git@github.com:hageldave/npy.git"
            developerConnection = "scm:git:git@github.com:hageldave/npy.git"
            url = "https://github.com/hageldave/npy"
        }
    }
}
